steps:
- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply
  args: ['apply', '-k', './k8smanifest/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=yassir-code-challenge-gke-dev'
    
 